-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. Create FEEDBACK table
create table feedback (
  id bigint generated by default as identity primary key,
  category text not null,
  message text not null,
  priority text default 'medium',
  status text default 'new',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create ADMINS table (Links to auth.users)
create table admins (
  id uuid references auth.users not null primary key,
  email text not null,
  role text default 'admin' check (role in ('admin', 'superadmin')),
  approved boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Security & RLS
alter table feedback enable row level security;
alter table admins enable row level security;

-- POLICY: Feedback
-- Everyone can submit (Anonymous)
create policy "Allow Anonymous Submission" 
  on feedback for insert 
  with check (true);

-- Only Approved Admins can View/Modify Feedback
create policy "Allow Approved Admins to View" 
  on feedback for select 
  using (
    exists (
      select 1 from admins 
      where admins.id = auth.uid() 
      and admins.approved = true
    )
  );

create policy "Allow Approved Admins to Update" 
  on feedback for update 
  using (
    exists (
      select 1 from admins 
      where admins.id = auth.uid() 
      and admins.approved = true
    )
  );

create policy "Allow Approved Admins to Delete" 
  on feedback for delete 
  using (
    exists (
      select 1 from admins 
      where admins.id = auth.uid() 
      and admins.approved = true
    )
  );

-- POLICY: Admins Table
-- Admins can read their own data (to check approval status)
create policy "Allow Self Read" 
  on admins for select 
  using (auth.uid() = id);

-- Superadmins can manage all admin records
create policy "Allow Superadmin Full Access" 
  on admins for all 
  using (
    exists (
      select 1 from admins a
      where a.id = auth.uid() 
      and a.role = 'superadmin' 
      and a.approved = true
    )
  );

-- 4. Trigger to auto-create admin entry on SignUp
-- (Optional: You might want to manually create admins, but this automates the link)
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  if new.email = 'mailtomohammedirfank@gmail.com' then
      insert into public.admins (id, email, approved, role)
      values (new.id, new.email, true, 'superadmin');
  else
      insert into public.admins (id, email, approved, role)
      values (new.id, new.email, false, 'admin');
  end if;
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
