-- 1. Create ADMIN_LOGS table
create table admin_logs (
  id bigint generated by default as identity primary key,
  admin_id uuid references auth.users not null,
  action text not null,
  details text,
  ip_address text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Enable RLS
alter table admin_logs enable row level security;

-- 3. Policies for Logs
-- Admins can insert logs (Self-logging actions)
create policy "Allow Admins to Log" 
  on admin_logs for insert 
  with check (auth.uid() = admin_id);

-- Only Superadmins can view logs
create policy "Allow Superadmin to View Logs" 
  on admin_logs for select 
  using (is_superadmin());

-- 4. Helper to log actions easily (Optional, can be done in backend)
-- We will handle logging primarily in the Node.js backend to capture IP easily.
