-- GOD MODE V2 SCHEMA (UPDATED)

-- 1. Access Logs (Total Surveillance)
CREATE TABLE IF NOT EXISTS public.access_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip_address TEXT,
    method TEXT,
    path TEXT,
    status_code INT,
    duration_ms INT,
    user_agent TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    metadata JSONB
);

ALTER TABLE public.access_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Superadmin read access_logs" ON public.access_logs;
CREATE POLICY "Superadmin read access_logs" ON public.access_logs
FOR SELECT USING (
  exists (
    select 1 from admins
    where admins.id = auth.uid()
    and admins.role = 'superadmin'
  )
);

-- Allow Insert (for Anon/Auth logging from backend)
DROP POLICY IF EXISTS "Allow insertion for logging" ON public.access_logs;
CREATE POLICY "Allow insertion for logging" ON public.access_logs
FOR INSERT WITH CHECK (true);

-- 2. Invited Emails
CREATE TABLE IF NOT EXISTS public.invited_emails (
    email TEXT PRIMARY KEY,
    invited_by UUID REFERENCES public.admins(id),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.invited_emails ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Superadmin full access invited_emails" ON public.invited_emails;
CREATE POLICY "Superadmin full access invited_emails" ON public.invited_emails
USING (
  exists (
    select 1 from admins
    where admins.id = auth.uid()
    and admins.role = 'superadmin'
  )
);

-- 3. Auto-Approval Trigger
-- When a new user is inserted into 'admins' (which happens via manual process or we need a trigger on auth.users),
-- WAIT. We don't have a trigger that inserts into 'admins' on Signup yet.
-- Users usually have to be manually added to 'admins'? Or do we assume 'admins' is just an extension?
-- Let's create a trigger: When User Signs Up, insert into 'admins'.
-- IF email is in 'invited_emails', set approved = true. Else false.

CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
DECLARE
  is_invited BOOLEAN;
BEGIN
  SELECT EXISTS(SELECT 1 FROM public.invited_emails WHERE email = new.email) INTO is_invited;
  
  INSERT INTO public.admins (id, email, role, approved)
  VALUES (new.id, new.email, 'admin', is_invited);
  
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger on auth.users
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 4. Feedback IP Column
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'feedback' AND column_name = 'ip_address') THEN
        ALTER TABLE public.feedback ADD COLUMN ip_address TEXT;
    END IF;
END $$;
