-- GOD MODE V2 & V3 CONSOLIDATED SCHEMA
-- RUN THIS SCRIPT TO FIX "relation does not exist" ERRORS

-- 1. Access Logs (Total Surveillance + Deep Inspection)
CREATE TABLE IF NOT EXISTS public.access_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip_address TEXT,
    method TEXT,
    path TEXT,
    status_code INT,
    duration_ms INT,
    user_agent TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    metadata JSONB,
    -- V3 Columns
    request_body JSONB,
    query_params JSONB,
    headers JSONB
);

-- RLS: Superadmin Read Only
ALTER TABLE public.access_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Superadmin read access_logs" ON public.access_logs;
CREATE POLICY "Superadmin read access_logs" ON public.access_logs
FOR SELECT USING (
  exists (
    select 1 from admins
    where admins.id = auth.uid()
    and admins.role = 'superadmin'
  )
);

-- Allow Insert (for Anon/Auth logging from backend)
DROP POLICY IF EXISTS "Allow insertion for logging" ON public.access_logs;
CREATE POLICY "Allow insertion for logging" ON public.access_logs
FOR INSERT WITH CHECK (true);

-- 2. Invited Emails (Pre-Approval Whitelist)
CREATE TABLE IF NOT EXISTS public.invited_emails (
    email TEXT PRIMARY KEY,
    invited_by UUID REFERENCES public.admins(id),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.invited_emails ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Superadmin full access invited_emails" ON public.invited_emails;
CREATE POLICY "Superadmin full access invited_emails" ON public.invited_emails
USING (
  exists (
    select 1 from admins
    where admins.id = auth.uid()
    and admins.role = 'superadmin'
  )
);

-- 3. Auto-Approval Trigger (The "Invite Agent" Logic)
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
DECLARE
  is_invited BOOLEAN;
BEGIN
  -- Check if email is in whitelist
  SELECT EXISTS(SELECT 1 FROM public.invited_emails WHERE email = new.email) INTO is_invited;
  
  -- Insert into admins (auto-approve if invited)
  INSERT INTO public.admins (id, email, role, approved)
  VALUES (new.id, new.email, 'admin', is_invited);
  
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger on auth.users (Safe to drop/recreate)
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 4. Admin Logs (Diff Support)
ALTER TABLE public.admin_logs ADD COLUMN IF NOT EXISTS changes JSONB;

-- 5. Feedback IP Column
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'feedback' AND column_name = 'ip_address') THEN
        ALTER TABLE public.feedback ADD COLUMN ip_address TEXT;
    END IF;
END $$;
